---
name: changelog
permissions: write-all
on:
  push:
    tags:
      - "*"
jobs:
  changelog:
    uses: clouddrove/github-shared-workflows/.github/workflows/release-changelog.yml@master
    with:
      branch: 'master'
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
...
