---
name: YAML-LINTER
on: [pull_request]

jobs:
  YAML-LINTER:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: üîç yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_file: .yamllint.yml
...
